spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/dto
    username: postgres
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

server:
  port: 8080

  error:
    include-stacktrace: always


security:
  jwt:
    secret: Java12
